# Generated by Django 5.0.3 on 2024-03-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0003_post_author_post_ismostliked_alter_post_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
