# Generated by Django 5.0.3 on 2024-04-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0009_tag_remove_author_address_remove_post_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('review', models.TextField()),
                ('rate', models.IntegerField()),
            ],
        ),
    ]
