# Generated by Django 5.0.3 on 2024-04-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0011_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_name',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='files',
            name='image',
            field=models.ImageField(upload_to='iamge'),
        ),
    ]
